package juruaplikasi;

import controller.InputMasukParkirController;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Timer;
import java.util.TimerTask;
import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Andhika Prameswara <prameswaara@gmail.com>
 */
public class InputMasukParkir extends javax.swing.JFrame {

    /**
     * Creates new form InputMasukParkir
     */
    Timer timer;
    DefaultTableModel model;
    InputMasukParkirController controller;

    public InputMasukParkir() {
        model = new DefaultTableModel();
        controller = new InputMasukParkirController(this);
        initComponents();
        initTableComponents();
        sinkronWaktu();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        labelJenisKendaraan = new javax.swing.JLabel();
        labelPlatMotor = new javax.swing.JLabel();
        fieldPlatMotor = new javax.swing.JTextField();
        comboBoxJenisKendaraan = new javax.swing.JComboBox<>();
        labelTanggal = new javax.swing.JLabel();
        fieldTanggal = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelParkirMasuk = new javax.swing.JTable();
        buttonTambah = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("FORM INPUT KENDARAAN MASUK");

        labelJenisKendaraan.setText("JENIS KENDARAAN");

        labelPlatMotor.setText("PLAT NOMOR");

        fieldPlatMotor.setText("jTextField1");
        fieldPlatMotor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldPlatMotorActionPerformed(evt);
            }
        });

        comboBoxJenisKendaraan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MOTOR", "MOBIL", "VIP" }));
        comboBoxJenisKendaraan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxJenisKendaraanActionPerformed(evt);
            }
        });

        labelTanggal.setText("TANGGAL/JAM");

        fieldTanggal.setText("Tolong tunggu");

        tabelParkirMasuk.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "KODE PARKIR", "KENDARAAN", "PLAT NOMOR", "TANGGAL MASUK"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelParkirMasuk);

        buttonTambah.setText("TAMBAH");
        buttonTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTambahActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelJenisKendaraan)
                            .addComponent(labelTanggal)
                            .addComponent(labelPlatMotor))
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(fieldPlatMotor)
                            .addComponent(comboBoxJenisKendaraan, 0, 186, Short.MAX_VALUE)
                            .addComponent(fieldTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelJenisKendaraan)
                            .addComponent(comboBoxJenisKendaraan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelPlatMotor)
                            .addComponent(fieldPlatMotor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelTanggal)
                            .addComponent(fieldTanggal))
                        .addGap(42, 42, 42)
                        .addComponent(buttonTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(65, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTambahActionPerformed
        // TODO add your handling code here:
        System.out.println("gas");
        String jenisKendaraan = comboBoxJenisKendaraan.getSelectedItem().toString();
        String platNomer = fieldPlatMotor.getText();
        String waktu = new SimpleDateFormat("dd MMM yyyy h:m:ss").format(new Date());
        controller.save(jenisKendaraan, platNomer, waktu);
        System.out.println("gas");
    }//GEN-LAST:event_buttonTambahActionPerformed

    private void comboBoxJenisKendaraanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxJenisKendaraanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxJenisKendaraanActionPerformed

    private void fieldPlatMotorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldPlatMotorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldPlatMotorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InputMasukParkir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InputMasukParkir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InputMasukParkir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InputMasukParkir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InputMasukParkir().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton buttonTambah;
    private javax.swing.JComboBox<String> comboBoxJenisKendaraan;
    private javax.swing.JTextField fieldPlatMotor;
    private javax.swing.JLabel fieldTanggal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelJenisKendaraan;
    private javax.swing.JLabel labelPlatMotor;
    private javax.swing.JLabel labelTanggal;
    private javax.swing.JTable tabelParkirMasuk;
    // End of variables declaration//GEN-END:variables

    private void sinkronWaktu() {
        timer = new Timer();
        timer.scheduleAtFixedRate(new TimerTask() {
            @Override
            public void run() {
                fieldTanggal.setText(new SimpleDateFormat("dd MMM yyyy h:m:ss").format(new Date()));
            }
        }, 0, 1000);
    }

    public DefaultTableModel getModel() {
        return model;
    }

    public void setModel(DefaultTableModel model) {
        this.model = model;
    }

    public JTable getTabelParkirMasuk() {
        return tabelParkirMasuk;
    }

    public void setTabelParkirMasuk(JTable tabelParkirMasuk) {
        this.tabelParkirMasuk = tabelParkirMasuk;
    }

    private void initTableComponents() {
        model.setColumnIdentifiers(new Object[]{
            "KODE PARKIR", "KENDARAAN", "PLAT NOMOR", "TANGGAL MASUK"
        });
        tabelParkirMasuk.setModel(model);
    }

    public JButton getButtonTambah() {
        return buttonTambah;
    }

    public void setButtonTambah(JButton buttonTambah) {
        this.buttonTambah = buttonTambah;
    }

}
