package juruaplikasi;

import controller.ParkirController;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Timer;
import java.util.TimerTask;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Andhika Prameswara <prameswaara@gmail.com>
 */
public class ParkirSistem extends javax.swing.JFrame {

    /**
     * Creates new form ParkirSistem
     */
    ParkirController controller;
    Timer timer;
    DefaultTableModel modelParkirMasuk, modelParkirKeluar;

    public ParkirSistem() {
        initComponents();
        modelParkirMasuk = new DefaultTableModel();
        modelParkirKeluar = new DefaultTableModel();
        controller = new ParkirController(this);
        initTableComponents();
        sinkronWaktu();

    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        labelJenisKendaraan = new javax.swing.JLabel();
        labelPlatMotor = new javax.swing.JLabel();
        fieldPlatMotor = new javax.swing.JTextField();
        comboBoxJenisKendaraan = new javax.swing.JComboBox<>();
        labelTanggal = new javax.swing.JLabel();
        fieldTanggal = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelParkirMasuk = new javax.swing.JTable();
        btnInputParkirMasuk = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        fieldKodeParkir = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelParkirKeluar = new javax.swing.JTable();
        fieldWaktuKeluar = new javax.swing.JSpinner();
        btnInputParkirKeluar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelJenisKendaraan.setText("JENIS KENDARAAN");

        labelPlatMotor.setText("PLAT NOMOR");

        fieldPlatMotor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldPlatMotorActionPerformed(evt);
            }
        });

        comboBoxJenisKendaraan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- PILIH KENDARAAN", "MOTOR", "MOBIL", "VIP" }));
        comboBoxJenisKendaraan.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboBoxJenisKendaraanItemStateChanged(evt);
            }
        });
        comboBoxJenisKendaraan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxJenisKendaraanActionPerformed(evt);
            }
        });

        labelTanggal.setText("TANGGAL/JAM");

        fieldTanggal.setText("Tolong tunggu");

        tabelParkirMasuk.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "KODE PARKIR", "KENDARAAN", "PLAT NOMOR", "TANGGAL MASUK"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelParkirMasuk);

        btnInputParkirMasuk.setText("TAMBAH");
        btnInputParkirMasuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInputParkirMasukActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnInputParkirMasuk, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelJenisKendaraan)
                            .addComponent(labelTanggal)
                            .addComponent(labelPlatMotor))
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(fieldPlatMotor)
                            .addComponent(comboBoxJenisKendaraan, 0, 186, Short.MAX_VALUE)
                            .addComponent(fieldTanggal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 585, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelJenisKendaraan)
                            .addComponent(comboBoxJenisKendaraan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelPlatMotor)
                            .addComponent(fieldPlatMotor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelTanggal)
                            .addComponent(fieldTanggal))
                        .addGap(42, 42, 42)
                        .addComponent(btnInputParkirMasuk, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(99, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("KENDARAAN MASUK", jPanel1);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("KODE PARKIR");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("WAKTU");

        fieldKodeParkir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldKodeParkirActionPerformed(evt);
            }
        });

        tabelParkirKeluar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "KODE PARKIR", "TANGGAL MASUK", "TANGGAL KELUARAN", "TARIF"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tabelParkirKeluar);

        fieldWaktuKeluar.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(1688626248087L), null, null, java.util.Calendar.DAY_OF_MONTH));

        btnInputParkirKeluar.setText("INPUT");
        btnInputParkirKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInputParkirKeluarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(fieldKodeParkir)
                            .addComponent(fieldWaktuKeluar)))
                    .addComponent(btnInputParkirKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 668, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(fieldKodeParkir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(fieldWaktuKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43)
                        .addComponent(btnInputParkirKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(100, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("KENDARAAN KELUAR", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fieldPlatMotorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldPlatMotorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldPlatMotorActionPerformed

    private void comboBoxJenisKendaraanItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboBoxJenisKendaraanItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxJenisKendaraanItemStateChanged

    private void comboBoxJenisKendaraanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxJenisKendaraanActionPerformed
        // TODO add your handling code here:
        String value = comboBoxJenisKendaraan.getSelectedItem().toString();
        controller.isFull(value);
    }//GEN-LAST:event_comboBoxJenisKendaraanActionPerformed

    private void btnInputParkirMasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInputParkirMasukActionPerformed
        // TODO add your handling code here:
        String jenisKendaraan = comboBoxJenisKendaraan.getSelectedItem().toString();
        String platNomer = fieldPlatMotor.getText();
        Date waktu = new Date();
        if ((!jenisKendaraan.equalsIgnoreCase("- PILIH KENDARAAN")) && (!platNomer.isBlank())) {
            controller.saveParkirMasuk(jenisKendaraan, platNomer, waktu);
        } else {
            JOptionPane.showOptionDialog(this, "TOLONG MASUKAN INPUT YANG LENGKAP", "Peringatan", JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE, null, null, null);
        }
    }//GEN-LAST:event_btnInputParkirMasukActionPerformed

    private void btnInputParkirKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInputParkirKeluarActionPerformed
        // TODO add your handling code here:
        String kode = fieldKodeParkir.getText();
        Date selectedDate = (Date) fieldWaktuKeluar.getValue();
        try {
            controller.saveParkirKeluar(kode, selectedDate);
        } catch (ParseException ex) {
            Logger.getLogger(ParkirSistem.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnInputParkirKeluarActionPerformed

    private void fieldKodeParkirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldKodeParkirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldKodeParkirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ParkirSistem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ParkirSistem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ParkirSistem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ParkirSistem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ParkirSistem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInputParkirKeluar;
    private javax.swing.JButton btnInputParkirMasuk;
    private javax.swing.JComboBox<String> comboBoxJenisKendaraan;
    private javax.swing.JTextField fieldKodeParkir;
    private javax.swing.JTextField fieldPlatMotor;
    private javax.swing.JLabel fieldTanggal;
    private javax.swing.JSpinner fieldWaktuKeluar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel labelJenisKendaraan;
    private javax.swing.JLabel labelPlatMotor;
    private javax.swing.JLabel labelTanggal;
    private javax.swing.JTable tabelParkirKeluar;
    private javax.swing.JTable tabelParkirMasuk;
    // End of variables declaration//GEN-END:variables

    private void sinkronWaktu() {
        timer = new Timer();
        timer.scheduleAtFixedRate(new TimerTask() {
            @Override
            public void run() {
                fieldTanggal.setText(new SimpleDateFormat("dd MMM yyyy h:m:ss").format(new Date()));
            }
        }, 0, 1000);
    }

    public DefaultTableModel getModelParkirMasuk() {
        return modelParkirMasuk;
    }

    public void setModelParkirMasuk(DefaultTableModel model) {
        this.modelParkirMasuk = model;
    }

    public DefaultTableModel getModelParkirKeluar() {
        return modelParkirKeluar;
    }

    public void setModelParkirKeluar(DefaultTableModel modelParkirKeluar) {
        this.modelParkirKeluar = modelParkirKeluar;
    }

    public JTable getTabelParkirKeluar() {
        return tabelParkirKeluar;
    }

    public void setTabelParkirKeluar(JTable tabelParkirKeluar) {
        this.tabelParkirKeluar = tabelParkirKeluar;
    }

    public JTable getTabelParkirMasuk() {
        return tabelParkirMasuk;
    }

    public void setTabelParkirMasuk(JTable tabelParkirMasuk) {
        this.tabelParkirMasuk = tabelParkirMasuk;
    }

    private void initTableComponents() {
        modelParkirMasuk.setColumnIdentifiers(new Object[]{
            "KODE PARKIR", "KENDARAAN", "PLAT NOMOR", "TANGGAL MASUK"
        });
        tabelParkirMasuk.setModel(modelParkirMasuk);
        modelParkirKeluar.setColumnIdentifiers(new Object[]{
            "KODE PARKIR", "TANGGAL MASUK", "TANGGAL KELUAR", "TARIF"
        });
        tabelParkirKeluar.setModel(modelParkirKeluar);
    }

    public JButton getButtonTambah() {
        return btnInputParkirMasuk;
    }

    public void setButtonTambah(JButton buttonTambah) {
        this.btnInputParkirMasuk = buttonTambah;
    }

}
